version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:15"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4"
    env_file:
      - ./database.dev.env
    ports:
      - "5050:80"
    networks: 
      - backend
  keycloak:
    container_name: keycloak
    image: "keycloak"
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
